DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS shop;
DROP TABLE IF EXISTS profile;

CREATE TABLE profile (
	profileId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	profileUserName VARCHAR(128) NOT NULL,
	profileSalt CHAR(64) NOT NULL,
	profileHash CHAR(128) NOT NULL,
	UNIQUE(profileUserName),
	PRIMARY KEY (profileId)
);

CREATE TABLE shop (
	shopId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	shopProfileId INT UNSIGNED NOT NULL,
	shopName VARCHAR(128) NOT NULL,
	shopEmail VARCHAR(128) NOT NULL,
	UNIQUE(shopEmail),
	FOREIGN KEY(shopProfileId) REFERENCES profile(profileId),
	PRIMARY KEY(shopId)
);

CREATE TABLE item(
	itemId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	itemShopId INT UNSIGNED NOT NULL,
	itemDescription VARCHAR(128) NOT NULL,
	itemPrice DECIMAL(12,2),
	FOREIGN KEY (itemShopId) REFERENCES shop(shopId),
	PRIMARY KEY (itemId)
);




